### ISSUE TITLE
! Error: Expecting value

### ISSUE THREAD

**Issue by SirGryphin** [dipu-bd/lightnovel-crawler#131] opened 2019-05-02 01:09 UTC
When trying to download "The Godsfall Chronicles" novel from novelfull.com I keep getting this kind of error, it seems to be different every time.

`! Error: Expecting value: line 1 column 1 (char 0)`
`! Error: Extra data: line 1 column 13627 (char 13626)`
`! Error: Extra data: line 1 column 12624 (char 12623)`
`! Error: Extra data: line 1 column 13199 (char 13198)`

Once in a while it might finish downloading without a problem, I've also noticed if I used the actual site URL it seems to download okay I get errors when using the search feature then selecting that site to download from. I've tried other sites/sources and it downloads okay.

- Novel URL: http://novelfull.com/the-godsfall-chronicles.html
- App Version: [e.g. 2.9.6]
- Package: PIP
- OS: Windows 10

**Comment by yudilee** [comment] 2019-05-02 02:13
I think maybe problem with windows 10, i try it using ubuntu and everything seems fine, cannot reproduce the bug 
`================================================================================
                           📒 Lightnovel Crawler 🍀2.9.6 
            Download lightnovels into html, text, epub, mobi and json 
--------------------------------------------------------------------------------

⮕ Press  Ctrl + C  to exit

? Enter novel page url or query novel:  godsfall chronicles
Searching |███████████████                 | 7/15https://readnovelfull.com/search?keyword=godsfall+chronicles
Searching |████████████████████████████████| 15/15
? Which one is your novel?  1. The Godsfall Chronicles [in 7 sources]
? Choose a source to download?  1. http://novelfull.com/the-godsfall-chronicles.html
Retrieving novel info...
NOVEL: The Godsfall Chronicles
? Enter output direcotry:  /var/www/html/Lightnovel/Lightnovels/novelfull-com/The Godsfall Chronicles
? Which chapters to download?  Everything! (425 chapters)
? Generate separate files for each volumes?  No
Downloading chapters |████████████████████████████████| 425/425
Created: 425 text files
Created: 425 html files
Created: The Godsfall Chronicles c1-335.epub
Created: The Godsfall Chronicles c1-335.mobi
Created: The Godsfall Chronicles c1-335.pdf
Created: The Godsfall Chronicles c1-335.docx
✨ Task completed  
`

**Comment by dipu-bd** [comment] 2019-05-02 04:46
I will test in on my windows PC tonight and maybe by tomorrow it will be fixed

**Comment by dipu-bd** [comment] 2019-05-05 02:24
I tried this on Windows. But I am not able to reproduce the issue. Did you try using virtual environment? Please give it a try using new virtual environment and let us know the result.

https://www.techcoil.com/blog/how-to-create-a-python-3-virtual-environment-in-windows-10/

**Comment by SirGryphin** [comment] 2019-05-05 10:15
I created a Virtual Environment and it seems to work okay, which I guess it means there is something install with my normal python that is causing there error. I will have to do a clean install of python or something and try again.

**Comment by dipu-bd** [comment] 2019-05-05 14:37
This kind of problem happens often with pip packaging system. Using a virtual environment to run separate programs is good practice. Closing this issue since it is solved.

**Closed by dipu-bd** 2019-05-05 14:37 UTC
Labels: bug
