### ISSUE TITLE
https://www.xunovel.com/

### ISSUE THREAD

**Issue by levinuiiy** [dipu-bd/lightnovel-crawler#1774] opened 2022-11-16 03:56 UTC
No, & checked it was not requested yet

- Language: English 
- Supports Searching: Yes
- Contains Machine Translations: Yes
- Contains Manga/Manhua/Manhwa: No
- Has CloudFlare Protection: i think No, since i didn't see any of it pop up, [& also Has alot of MTL Novels]

**Comment by dipu-bd** [comment] 2022-11-24 04:36
Duplicate of #1703

**Closed by dipu-bd** 2022-11-24 04:36 UTC
Labels: source
