### ISSUE TITLE
https://read.asianovel.com/series/the-boss-i-picked-up-all-fell-in-love-with-me

### ISSUE THREAD

**Issue by Xiaowang78** [dipu-bd/lightnovel-crawler#727] opened 2021-01-22 06:11 UTC

**Comment by dipu-bd** [comment] 2021-01-22 11:50
@Xiaowang78 can you add some description about this issue? 

I guess you wanted to report a bug. Go over here for reporting bugs: https://github.com/dipu-bd/lightnovel-crawler/issues/new?assignees=&labels=bug&template=bug_report.md&title=Fix+this+bug

**Comment by dipu-bd** [comment] 2021-02-18 04:49
Duplicate of #734

**Closed by dipu-bd** 2021-02-18 04:49 UTC
Labels: source
