### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by idMysteries** [dipu-bd/lightnovel-crawler#1651] opened 2022-09-28 14:04 UTC
![image](https://user-images.githubusercontent.com/11484976/192799779-a55f3af9-355d-4281-9134-a06a1849f163.png)

**Comment by dipu-bd** [comment] 2022-09-28 16:24
It says cancelled by user.

**Comment by idMysteries** [comment] 2022-09-28 16:33
Ctrl + C...
choose another: no

**Comment by dipu-bd** [comment] 2022-09-28 17:52
Can you describe the steps to reproduce?

**Comment by idMysteries** [comment] 2022-09-28 18:06
1. Search novel
2. Ctrl + C
3. choose another? No
4. ...
5. PROFIT

**Comment by dipu-bd** [comment] 2022-09-28 19:41
I can't reproduce it following your steps.

**Comment by dipu-bd** [comment] 2022-09-28 19:42
I finally reproduced it. But it happened when pressing Ctrl + C twice. Which is expected. Need to just change the error message.

**Comment by idMysteries** [comment] 2022-09-28 19:48
I have an error after pressing Ctrl+C once

**Comment by dipu-bd** [comment] 2022-09-28 19:49
Try now. It should work. If it does not it is a feature not a bug 😆

**Comment by idMysteries** [comment] 2022-09-28 19:53
![image](https://user-images.githubusercontent.com/11484976/192876021-eb5cef47-17c7-4d49-b12e-a60f6d45678d.png)

**Comment by idMysteries** [comment] 2022-09-28 19:57
![image](https://user-images.githubusercontent.com/11484976/192876716-5c044924-a0ce-4f8b-b75e-08860e0a346f.png)

**Comment by idMysteries** [comment] 2022-09-28 20:00
``` py
answer = prompt(
            [
                {
                    "type": "list",
                    "name": "novel",
                    "message": "Which one is your novel?",
                    "choices": display.format_novel_choices(choices),
                }
            ]
        )

        index = int(answer["novel"].split(".")[0]) <----- need check for 'novel'
```

**Comment by dipu-bd** [comment] 2022-09-28 20:27
I found the issue. It should be fixed now.

**Closed** 2022-09-28 20:48 UTC
Labels: bug
