### ISSUE TITLE
https://goblinsguide.com

### ISSUE THREAD

**Issue by estevamprada** [dipu-bd/lightnovel-crawler#1966] opened 2023-05-24 16:16 UTC
- Language: English / Spanish
- Supports Searching: Yes
- Contains Machine Translations: Yes
- Contains Manga/Manhua/Manhwa: No
- Has CloudFlare Protection: No

**Comment by dipu-bd** [comment] 2023-07-01 06:46
Duplicate of #937

**Closed by dipu-bd** 2023-07-01 06:46 UTC
Labels: source
