### ISSUE TITLE
https://mtlnation.com/

### ISSUE THREAD

**Issue by mynamex1** [dipu-bd/lightnovel-crawler#1387] opened 2022-06-13 04:07 UTC
- Language: english
- Supports Searching: Yes
- Contains Machine Translations: No
- Contains Manga/Manhua/Manhwa: No
- Has CloudFlare Protection: Yes/No

**Comment by dipu-bd** [comment] 2022-06-14 11:30
Duplicate of #1236

**Closed by dipu-bd** 2022-06-14 11:30 UTC
Labels: source
