### ISSUE TITLE
https://wanderinginn.com/table-of-contents/

### ISSUE THREAD

**Issue by wizerdo37** [dipu-bd/lightnovel-crawler#1958] opened 2023-05-11 21:58 UTC
Web serial URL:
https://wanderinginn.com/table-of-contents/

App Location: PIP | EXE | Discord | Telegram
EXE - Discord

App Version: x.y.z
Latest Docker Build : Lightnovel Crawler 3.2.6

Describe this issue
the app is Unable to download from https://wanderinginn.com/table-of-contents/

EXE

![image](https://github.com/dipu-bd/lightnovel-crawler/assets/91095960/c17e535b-cf94-493f-b51c-5d5f69f7f323)

-------------------

Discord 

![image](https://github.com/dipu-bd/lightnovel-crawler/assets/91095960/19af880f-1a8b-492c-a641-98ac5963a70f)

**Comment by dipu-bd** [comment] 2023-07-01 06:49
Duplicate of #1067

**Closed by dipu-bd** 2023-07-01 06:49 UTC
Labels: source-issue

**Comment by arromdee** [comment] 2023-09-24 21:13
Still can't in 3.3.0.  

```
/home/arromdee/tmp% lncrawl
================================================================================
╭╮╱╱╱╱╱╱╭╮╱╭╮╱╱╱╱╱╱╱╱╱╱╱╱╭╮╱╭━━━╮╱╱╱╱╱╱╱╱╱╭╮
┃┃╱╱╱╱╱╱┃┃╭╯╰╮╱╱╱╱╱╱╱╱╱╱╱┃┃╱┃╭━╮┃╱╱╱╱╱╱╱╱╱┃┃
┃┃╱╱╭┳━━┫╰┻╮╭╋━╮╭━━┳╮╭┳━━┫┃╱┃┃╱╰╋━┳━━┳╮╭╮╭┫┃╭━━┳━╮
┃┃╱╭╋┫╭╮┃╭╮┃┃┃╭╮┫╭╮┃╰╯┃┃━┫┃╱┃┃╱╭┫╭┫╭╮┃╰╯╰╯┃┃┃┃━┫╭╯
┃╰━╯┃┃╰╯┃┃┃┃╰┫┃┃┃╰╯┣╮╭┫┃━┫╰╮┃╰━╯┃┃┃╭╮┣╮╭╮╭┫╰┫┃━┫┃
╰━━━┻┻━╮┣╯╰┻━┻╯╰┻━━╯╰╯╰━━┻━╯╰━━━┻╯╰╯╰╯╰╯╰╯╰━┻━━┻╯
╱╱╱╱╱╭━╯┃ v3.3.0
╱╱╱╱╱╰━━╯ 🔗 https://github.com/dipu-bd/lightnovel-crawler
--------------------------------------------------------------------------------

➡ Press  Ctrl + C  to exit

? Enter novel page url or query novel: https://wanderinginn.com/table-of-contents/
 
Retrieving novel info...

 ❗ Error: No chapters found 
<class 'Exception'>
File "/home/arromdee/.local/lib/python3.10/site-packages/lncrawl/bots/console/integration.py", line 107, in start
    raise e
  File "/home/arromdee/.local/lib/python3.10/site-packages/lncrawl/bots/console/integration.py", line 101, in start
    _download_novel()
  File "/home/arromdee/.local/lib/python3.10/site-packages/lncrawl/bots/console/integration.py", line 85, in _download_novel
    self.app.get_novel_info()
  File "/home/arromdee/.local/lib/python3.10/site-packages/lncrawl/core/app.py", line 137, in get_novel_info
    raise Exception("No chapters found")


--------------------------------------------------------------------------------
 🔗  https://github.com/dipu-bd/lightnovel-crawler/issues 
================================================================================
/home/arromdee/tmp% 
```
