### ISSUE TITLE
https://foxaholic.com/

### ISSUE THREAD

**Issue by azurymous24** [dipu-bd/lightnovel-crawler#637] opened 2020-10-23 09:11 UTC
Please add this source please! It has a lot of novels and the translators are good.

**Comment by kuwoyuki** [comment] 2020-10-23 09:14
duplicate of https://github.com/dipu-bd/lightnovel-crawler/issues/631, https://github.com/dipu-bd/lightnovel-crawler/issues/471 and https://github.com/dipu-bd/lightnovel-crawler/issues/344

**Closed** 2020-10-24 13:15 UTC
Labels: source
