### ISSUE TITLE
https://novelroom.net 

### ISSUE THREAD

**Issue by read-novel** [dipu-bd/lightnovel-crawler#1416] opened 2022-06-29 15:46 UTC
Well , I hope you can add this website 

- Language: English 
- Supports Searching: Yes
- Contains Machine Translations: Yes
- Contains Manga/Manhua/Manhwa: No
- Has CloudFlare Protection: Yes/No

**Comment by dipu-bd** [comment] 2022-09-24 21:59
Duplicate of #1622

**Closed by dipu-bd** 2022-09-24 21:59 UTC
Labels: source
