### ISSUE TITLE
Fix this source : Mtlnation

### ISSUE THREAD

**Issue by Flwk** [dipu-bd/lightnovel-crawler#1453] opened 2022-08-04 11:02 UTC
Hello,

I have this error when i try to get a novel on MTLNATION

The novel : https://mtlnation.com/novel/villain-seized-the-assassin-heroine-at-the-start/

```
================================================================================
                          [#] Lightnovel Crawler v2.31.0
                  https://github.com/dipu-bd/lightnovel-crawler
--------------------------------------------------------------------------------

-> Press  Ctrl + C  to exit

? Enter novel page url or query novel: https://mtlnation.com/novel/villain-seized-the-assassin-heroine-at-the-start/
? Do you want to log in? Yes
? User/Email: *************
? Password: ***************
Retrieving novel info...
https://mtlnation.com/novel/villain-seized-the-assassin-heroine-at-the-start/

 ! Error: list indices must be integers or slices, not str
 <class 'TypeError'>
 File "lncrawl\bots\console\integration.py", line 89, in start
    _download_novel()
  File "lncrawl\bots\console\integration.py", line 78, in _download_novel
    self.app.get_novel_info()
  File "lncrawl\core\app.py", line 140, in get_novel_info
    self.crawler.read_novel_info()
  File "C:\Users\Bilal\.lncrawl\sources\en\m\mtlnation.py", line 55, in read_novel_info
    self.novel_title = data['data']['title']


--------------------------------------------------------------------------------
 -  https://github.com/dipu-bd/lightnovel-crawler/issues
================================================================================
Press ENTER to exit...
```

Thanks a lot !

**Comment by Flwk** [comment] 2022-08-25 21:23
@dipu-bd Hello,

I tried again,but it doesn't work : 

With login : 

`================================================================================
                          [#] Lightnovel Crawler v2.32.0
                  https://github.com/dipu-bd/lightnovel-crawler
--------------------------------------------------------------------------------

-> Press  Ctrl + C  to exit

? Enter novel page url or query novel: https://mtlnation.com/novel/is-the-big-villain-crazy-really-made-the-empress-int
o-a-puppet
? Do you want to log in? Yes
? User/Email: *****************
? Password: ***************

 ! Error: 503 Server Error: Service Temporarily Unavailable for url: https://api.mtlnation.com/api/v2/accounts/login
 <class 'requests.exceptions.HTTPError'>
 File "lncrawl\core\crawler.py", line 322, in post_json
    response = self.post_response(url, data, headers)
  File "lncrawl\core\crawler.py", line 262, in post_response
    return self.__process_response(response)
  File "lncrawl\core\crawler.py", line 207, in __process_response
    response.raise_for_status()
  File "requests\models.py", line 1021, in raise_for_status


--------------------------------------------------------------------------------
 -  https://github.com/dipu-bd/lightnovel-crawler/issues
================================================================================
Press ENTER to exit...`

Without login : 
`================================================================================
                          [#] Lightnovel Crawler v2.32.0
                  https://github.com/dipu-bd/lightnovel-crawler
--------------------------------------------------------------------------------

-> Press  Ctrl + C  to exit

? Enter novel page url or query novel: https://mtlnation.com/novel/is-the-big-villain-crazy-really-made-the-empress-int
o-a-puppet
? Do you want to log in? No
Retrieving novel info...
https://mtlnation.com/novel/is-the-big-villain-crazy-really-made-the-empress-into-a-puppet
NOVEL: Is The Big Villain Crazy, Really Made The Empress Into A Puppet?
6 volumes and 524 chapters found
? Enter output directory: C:\Users\Bilal\Downloads
? What to do with existing folder? Remove old folder and start fresh
? Which chapters to download? Everything! (524 chapters)
? 524 chapters selected Continue
? Which output formats to create? [epub]
? How many files to generate? Pack everything into a single file
Chapters:  19%|█████████████                                                       | 101/524 [00:06<00:26, 15.70item/s]

--------------------------------------------------------------------------------
 -  https://github.com/dipu-bd/lightnovel-crawler/issues
================================================================================
Press ENTER to exit...`

Thank you very much for all your works !

**Comment by idMysteries** [comment] 2022-08-26 07:35
@dipu-bd the problem is not in the source, but in the downloader.

![изображение](https://user-images.githubusercontent.com/11484976/186848378-61931f0a-d0d7-4fe9-8071-98b2779a9009.png)

**Comment by dipu-bd** [comment] 2022-08-26 07:43
Downloader has some issues. I already fixed it in a commit. It is pending to be merged with the master. 

The reported issue is different: `Error: 503 Server Error: Service Temporarily Unavailable for url: https://api.mtlnation.com/api/v2/accounts/login` We need to check if the link is not working anymore

**Comment by idMysteries** [comment] 2022-08-26 08:07
![изображение](https://user-images.githubusercontent.com/11484976/186854384-8c4d8485-2aec-43e2-ba47-0d633112d665.png)
Works, Close the issue

**Comment by idMysteries** [comment] 2022-08-26 08:18
![изображение](https://user-images.githubusercontent.com/11484976/186856701-3d9d2f13-b4b5-4b37-9ef0-3e30c6c173eb.png)

**Comment by idMysteries** [comment] 2022-08-26 08:26
![изображение](https://user-images.githubusercontent.com/11484976/186858256-4c1633ce-a60b-478f-8ffd-a2454bd1030d.png)

**Comment by dipu-bd** [comment] 2022-08-26 22:24
I checked that the login is okay. The 503 error is caused by cloudflare security. There is no easy way to solve it for now.

**Closed by dipu-bd** 2022-08-26 22:24 UTC
Labels: source-issue
