### ISSUE TITLE
https://kolnovel.com/

### ISSUE THREAD

**Issue by nissou1** [dipu-bd/lightnovel-crawler#1423] opened 2022-07-08 17:08 UTC
- Language: ar
- Supports Searching: Yes
- Contains Machine Translations: yes
- Contains Manga/Manhua/Manhwa: No
- Has CloudFlare Protection: Yes

**Comment by dipu-bd** [comment] 2022-07-15 23:12
Duplicate of #876

**Closed by dipu-bd** 2022-07-15 23:12 UTC
Labels: source
