### ISSUE TITLE
Fix this source - webnovel is not working 

### ISSUE THREAD

**Issue by read-novel** [dipu-bd/lightnovel-crawler#1400] opened 2022-06-17 16:22 UTC
Yes, i have read the issue but answer wasn't that much helpful 

## Let us know
Webnovel is not working its say zero chapter, whenever i past the link in the bot of disord it say zero chapter and all the member of crawler in discord are facing this problem. You can try yourself  in bot if you think i am telling lie then you can see the problem yourself 

**Novel URL**:     <https://m.webnovel.com/book/permanent-martial-arts_22182766305735005> 
**App Location**: -- Discord 
 
Well, we all are facing this issue in discord bot
At least 24 days has pass

   bot name - lightnovel crawler

## Describe this issue
Webnovel is not working it say zero chapter whenever i try to download any novel from webnovel 

 screenshots here
![Screenshot_20220617_213502](https://user-images.githubusercontent.com/107703937/174337952-81ea9ac4-8348-46e9-b3d5-53ba72cedf33.jpg)

**Comment by Trafford666** [comment] 2022-06-19 08:40
Same problem here

**Comment by budikesuma** [comment] 2022-06-24 05:58
@read-novel , @Trafford666 

Read this issue #1362

**Comment by dipu-bd** [comment] 2022-06-24 18:20
Duplicate of #1362

**Closed by dipu-bd** 2022-06-24 18:20 UTC
Labels: source-issue

**Comment by read-novel** [comment] 2022-06-25 06:21
> Duplicate of #1362

So when we can expect to solve this issue
