### ISSUE TITLE
Fix this source webnovel not working

### ISSUE THREAD

**Issue by Trafford666** [dipu-bd/lightnovel-crawler#1425] opened 2022-07-09 14:43 UTC
It was once here, but the Webnovel source is still not working... any solutions to this?

**Comment by Jemeni11** [comment] 2022-07-09 21:24
I have no idea when it will be fixed, but you can use [WebToEpub](https://github.com/dteviot/WebToEpub). 
How to use WebToEpub to download from WebNovel:  https://github.com/dteviot/WebToEpub/issues/754#issuecomment-1150327036

**Comment by dipu-bd** [comment] 2022-07-10 06:21
Duplicate of #1362

**Closed by dipu-bd** 2022-07-10 06:21 UTC
Labels: source-issue
