### ISSUE TITLE
https://www.novels.pl

### ISSUE THREAD

**Issue by XiaErrr** [dipu-bd/lightnovel-crawler#782] opened 2021-03-10 04:37 UTC
This website ( https://www.novels.pl ) has a couple of chapters ahead of other places for several series so it would be greatly appreciated if it could be added to the list of sources for the app ( and even better if the discord bot could use this source too for mobile users )

Thanks in advance.

**Comment by dipu-bd** [comment] 2021-04-24 10:02
duplicate of #441

**Closed by dipu-bd** 2021-04-24 10:02 UTC
Labels: source
