### ISSUE TITLE
https://panda-novel.com/

### ISSUE THREAD

**Issue by Sub2Assassin** [dipu-bd/lightnovel-crawler#1548] opened 2022-09-05 19:28 UTC
Please add this to the programme, it has latest novels which only has less than 50 chps on webnovel too.

- Language: English 
- Supports Searching: Yes
- Contains Machine Translations: No
- Contains Manga/Manhua/Manhwa: Yes
- Has CloudFlare Protection: idk

**Comment by Sub2Assassin** [comment] 2022-09-05 19:29
Idk about cloudflare protection btw.

**Comment by idMysteries** [comment] 2022-09-05 20:19
Copy https://github.com/dipu-bd/lightnovel-crawler/issues/1343

**Comment by Sub2Assassin** [comment] 2022-09-05 20:27
So is it already in process?

**Comment by dipu-bd** [comment] 2022-09-08 00:35
Duplicate of #1343

**Closed by dipu-bd** 2022-09-08 00:35 UTC
Labels: source
