### ISSUE TITLE
https://novel-bin.net/

### ISSUE THREAD

**Issue by novelkla** [dipu-bd/lightnovel-crawler#1975] opened 2023-06-10 02:38 UTC
- Language:
- Supports Searching: Yes/No
- Contains Machine Translations: Yes/No
- Contains Manga/Manhua/Manhwa: Yes/No
- Has CloudFlare Protection: Yes/No

**Comment by dipu-bd** [comment] 2023-07-01 06:40
Duplicate of #1976

**Closed by dipu-bd** 2023-07-01 06:40 UTC
Labels: source
