### ISSUE TITLE
Fix this source https://daotranslate.us/

### ISSUE THREAD

**Issue by Jcoth** [dipu-bd/lightnovel-crawler#2303] opened 2024-03-14 14:30 UTC
[Daotranslate.us was supposed to be a source](https://github.com/dipu-bd/lightnovel-crawler/issues/2159)

## Let us know

**Novel URL**:    (https://daotranslate.us/series/reaper-of-the-drifting-moon/)
**App Location**:    EXE | Discord 
**App Version**:  3.5.0 | Lighnovel Bot, Lightnovel Crawler

## Describe this issue

Source Not recognized

![Capture](https://github.com/dipu-bd/lightnovel-crawler/assets/152507714/cc8c4369-0c6e-4ae8-82db-f9e1fc97a9a5)

**Comment by zGadli** [comment] 2024-03-15 07:44
The issue is that the URL for the website has changed. This is an easy fix I'll make a pull request to fix this issue in a while. You can try to fork the code for this project and then edit a single line for the fix.

**Comment by Jcoth** [comment] 2024-03-15 12:49
Thank you for the answer @zGadli but i don't know how to code or compile, sorry for the inconvenience.

**Comment by zGadli** [comment] 2024-03-15 13:28
@Jcoth you'll have to wait for the updated version. if you want you can share your discord username and I could send you the downloaded chapters of the novel you want.

**Comment by Jcoth** [comment] 2024-03-15 13:33
I'll wait for the updated version thank you very much ! Feel free to close this issue whenever convenient.

**Comment by zGadli** [comment] 2024-03-15 14:50
@Jcoth you have to close the issue i can't.

**Closed** 2024-03-15 14:50 UTC
Labels: source-issue
