### ISSUE TITLE
Python crashes randomly when downloading novels

### ISSUE THREAD

**Issue by KiraYamatoSD** [dipu-bd/lightnovel-crawler#201] opened 2019-09-23 04:21 UTC
Hi, I want to ask if there is any way to debug what is causing python to crash?

I have tested many times, and there is no error bug

The script runs up to this and it randomly crashes.

```
Downloading to Z:\SharedFolder\python_apps\lightnovel-crawler\Lightnovels\babelnovel-com\World of Be
lles\json\Volume 01\00005.json
2019-09-23 11:27:36,677 [INFO] (BABELNOVEL)
Visiting https://babelnovel.com/api/books/world-of-belles/chapters/c5?ignoreTopic=true
2019-09-23 11:27:36,679 [DEBUG] (urllib3.connectionpool)
Starting new HTTPS connection (4): babelnovel.com:443
2019-09-23 11:27:36,662 [DEBUG] (DOWNLOADER)
Downloading to Z:\SharedFolder\python_apps\lightnovel-crawler\Lightnovels\babelnovel-com\World of Be
lles\json\Volume 01\00004.json
2019-09-23 11:27:36,677 [DEBUG] (urllib3.connectionpool)
Starting new HTTPS connection (3): babelnovel.com:443
2019-09-23 11:27:36,661 [DEBUG] (DOWNLOADER)
Downloading to Z:\SharedFolder\python_apps\lightnovel-crawler\Lightnovels\babelnovel-com\World of Be
lles\json\Volume 01\00003.json
2019-09-23 11:27:36,672 [INFO] (BABELNOVEL)
Visiting https://babelnovel.com/api/books/world-of-belles/chapters/c6?ignoreTopic=true
2019-09-23 11:27:36,684 [INFO] (BABELNOVEL)
Visiting https://babelnovel.com/api/books/world-of-belles/chapters/c4?ignoreTopic=true
2019-09-23 11:27:36,686 [INFO] (BABELNOVEL)
Visiting https://babelnovel.com/api/books/world-of-belles/chapters/c3?ignoreTopic=true
2019-09-23 11:27:36,689 [DEBUG] (urllib3.connectionpool)
Starting new HTTPS connection (5): babelnovel.com:443
2019-09-23 11:27:36,691 [DEBUG] (urllib3.connectionpool)
Starting new HTTPS connection (6): babelnovel.com:443
2019-09-23 11:27:36,694 [DEBUG] (urllib3.connectionpool)
Starting new HTTPS connection (7): babelnovel.com:443
2019-09-23 11:27:36,868 [DEBUG] (urllib3.connectionpool)
https://babelnovel.com:443 "GET /api/books/world-of-belles/chapters/c1?ignoreTopic=true HTTP/1.1" 20
0 None
2019-09-23 11:27:36,878 [DEBUG] (urllib3.connectionpool)
https://babelnovel.com:443 "GET /api/books/world-of-belles/chapters/c7?ignoreTopic=true HTTP/1.1" 20
0 None
2019-09-23 11:27:36,981 [DEBUG]
```

![image](https://user-images.githubusercontent.com/19279071/65401623-14161780-ddfc-11e9-8a31-7feecebd48ce.png)

**Comment by dipu-bd** [comment] 2019-09-23 15:51
that is a difficult bug. I will look into it

**Comment by dipu-bd** [comment] 2019-10-17 16:16
@KiraYamatoSD I uploaded a new version. please check it to see if this issue is still there. I could not reproduce this issue on my PC

**Comment by KiraYamatoSD** [comment] 2019-10-19 14:40
@dipu-bd After testing the new version, I have not encountered any crashes at this moment. 
Thank you very much for the update.

**Comment by dipu-bd** [comment] 2019-10-19 17:08
Okay, I am closing this issue for now. You can open it again if you see this issue.

**Closed by dipu-bd** 2019-10-19 17:08 UTC
