### ISSUE TITLE
https://riwyat.com/

### ISSUE THREAD

**Issue by Mahdi3002** [dipu-bd/lightnovel-crawler#1452] opened 2022-08-04 09:47 UTC
- Language:arabic
- Supports Searching: Yes
- Contains Machine Translations: some
- Contains Manga/Manhua/Manhwa: No, just novel
- Has CloudFlare Protection: i dont konw

**Comment by dipu-bd** [comment] 2022-08-08 21:23
Duplicate of #1140

**Closed by dipu-bd** 2022-08-08 21:23 UTC
Labels: source
