### ISSUE TITLE
wuxiaworld.eu

### ISSUE THREAD

**Issue by chiffonkla** [dipu-bd/lightnovel-crawler#2217] opened 2023-12-22 08:13 UTC
- Language:
- Supports Searching: Yes/No
- Contains Machine Translations: Yes/No
- Contains Manga/Manhua/Manhwa: Yes/No
- Has CloudFlare Protection: Yes/No

**Comment by camp00000** [comment] 2024-02-10 17:17
Duplicate of #2224 , please close this issue.

**Closed** 2024-02-12 06:27 UTC
Labels: source
