### ISSUE TITLE
[www.wuxiaworld.com] ElementClickInterceptedException: Message: element click intercepted

### ISSUE THREAD

**Issue by Vqid** [dipu-bd/lightnovel-crawler#1756] opened 2022-11-03 23:55 UTC
## Let us know

**Novel URL**:    https://www.wuxiaworld.com/novel/overgeared 
**App Location**:    EXE 
**App Version**:   3.0.1  

## Describe this issue

It stops a chapter 350 and gives the following error. Easy to replicate.

cloudscraper.exceptions.CloudflareChallengeError: Detected a Cloudflare version 2 Captcha challenge, This feature is not available in the opensource (free) version.

During handling of the above exception, another exception occurred:

selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 MuiAccordion-root MuiAccordion-rounded my-0 overflow-hidden overflow-clip rounded-none border-b-0 shadow-none first:rounded-none last:rounded-none dark:bg-[#202020] md:mb-[12px] md:rounded-[12px] md:bg-white md:shadow-ww-text-container md:first:rounded-[12px] md:last:rounded-[12px] md:dark:bg-gray-850 ww-1r7uzuu">...</div> is not clickable at point (623, 28). Other element would receive the click: <div class="mr-8 flex flex-1 items-center pt-[8px] sm:pt-0 sm:pl-[24px]">...</div>
  (Session info: chrome=107.0.5304.88)
Stacktrace:
Backtrace:
        Ordinal0 [0x010FACD3+2075859]
        Ordinal0 [0x0108EE61+1633889]
        Ordinal0 [0x00F8B7BD+571325]
        Ordinal0 [0x00FC1499+791705]
        Ordinal0 [0x00FBF4AC+783532]
        Ordinal0 [0x00FBD0AB+774315]
        Ordinal0 [0x00FBBD37+769335]
        Ordinal0 [0x00FB1C76+728182]
        Ordinal0 [0x00FD731C+881436]
        Ordinal0 [0x00FB15BF+726463]
        Ordinal0 [0x00FD7534+881972]
        Ordinal0 [0x00FEB56A+963946]
        Ordinal0 [0x00FD7136+880950]
        Ordinal0 [0x00FAFEFD+720637]
        Ordinal0 [0x00FB0F3F+724799]
        GetHandleVerifier [0x013AEED2+2769538]
        GetHandleVerifier [0x013A0D95+2711877]
        GetHandleVerifier [0x0118A03A+521194]
        GetHandleVerifier [0x01188DA0+516432]
        Ordinal0 [0x0109682C+1665068]
        Ordinal0 [0x0109B128+1683752]
        Ordinal0 [0x0109B215+1683989]
        Ordinal0 [0x010A6484+1729668]
        BaseThreadInitThunk [0x77446739+25]
        RtlGetFullPathName_UEx [0x77E18FD2+1218]
        RtlGetFullPathName_UEx [0x77E18F9D+1165]

**Comment by dipu-bd** [comment] 2022-11-04 07:10
Duplicate of #1708

**Closed by dipu-bd** 2022-11-04 07:10 UTC
Labels: source-issue
