### ISSUE TITLE
readlightnovel.org error

### ISSUE THREAD

**Issue by SirGryphin** [dipu-bd/lightnovel-crawler#257] opened 2019-12-04 15:44 UTC
When I paste URL I got a error about Node JS being out of date, so I updated node and now I get this error.

Everything downloads okay and epub works fine its just this error shows up.

```
? Enter novel page url or query novel:  https://www.readlightnovel.org/im-pregnant-with-the-villains-child
Retrieving novel info...
https://www.readlightnovel.org/im-pregnant-with-the-villains-child
Failed getting author: https://www.readlightnovel.org/im-pregnant-with-the-villains-child
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\lncrawl\spiders\readln.py", line 30, in read_novel_info
    "a[href*=author]").text.strip().title()
AttributeError: 'NoneType' object has no attribute 'text'
NOVEL: I’m Pregnant with the Villain’s Child
? Enter output direcotry:  C:\Users\User\Downloads\Lightnovels\www-readlightnovel-org\Im Pregnant with the Villains Chi
ld
? Which chapters to download?  Everything! (63 chapters)
? 63 chapters selected  Continue
? How many files to generate?  Pack everything into a single file
Downloading chapters |████████████████████████████████| 63/63
[?25hDownloaded 63 chapters
Created: Im Pregnant with the Villains Child c1-63.epub
* Task completed
```

- Novel URL: https://www.readlightnovel.org/im-pregnant-with-the-villains-child
- App Version: 2.17.0
- Package: pip
- OS: Windows 10

**Comment by dipu-bd** [comment] 2019-12-04 15:48
This novel has no author. So, it is failing to parse author information. But the error message should be hidden.

**Comment by SirGryphin** [comment] 2019-12-04 16:05
Okay thanks for letting me know.

**Comment by dipu-bd** [comment] 2019-12-04 17:58
Don't worry about it. After the issue is fixed, I will close it.

**Comment by dipu-bd** [comment] 2019-12-05 05:32
should be fixed by last commit

**Closed by dipu-bd** 2019-12-05 05:32 UTC
Labels: bug
