### ISSUE TITLE
Termux upgrade using pip stuck at version 2.34.0

### ISSUE THREAD

**Issue by mygithub-acct** [dipu-bd/lightnovel-crawler#1716] opened 2022-10-12 10:29 UTC
When trying to upgrade lightnovel-crawler in termux it remains at version 2.34.0

$ pip install -U lightnovel-crawler                     Requirement already satisfied: lightnovel-crawler in /data/data/com.termux/files/usr/lib/python3.10/site-packages (2.34.0)                                              Collecting lightnovel-crawler
  Using cached lightnovel_crawler-3.0.1-py3-none-any.whl (500 kB)
Requirement already satisfied: python-slugify<7.0.0,>=4.0.0 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from lightnovel-crawler) (6.1.2)           Requirement already satisfied: js2py==0.71 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from lightnovel-crawler) (0.71)
Requirement already satisfied: packaging in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from lightnovel-crawler) (21.3)
Requirement already satisfied: tqdm<5.0,>=4.60 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from lightnovel-crawler) (4.64.1)
Requirement already satisfied: questionary>=1.6.0 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from lightnovel-crawler) (1.10.0)                    Requirement already satisfied: cloudscraper>=1.2.60 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from lightnovel-crawler) (1.2.64)                  Requirement already satisfied: prompt-toolkit~=3.0 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from lightnovel-crawler) (3.0.31)                   Requirement already satisfied: html5lib~=1.1 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from lightnovel-crawler) (1.1)                            Requirement already satisfied: python-dotenv<1.0.0,>=0.15.0 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from lightnovel-crawler) (0.21.0)          Requirement already satisfied: base58~=2.1.1 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from lightnovel-crawler) (2.1.1)                          Requirement already satisfied: pillow>=6.0.0 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from lightnovel-crawler) (9.2.0)                          Requirement already satisfied: colorama<0.5.0,>=0.4.0 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from lightnovel-crawler) (0.4.5)
Collecting python-box<7.0.0,>=6.0.0
  Using cached python_box-6.0.2-py3-none-any.whl (26 kB)
Collecting webdriver-manager
  Using cached webdriver_manager-3.8.3-py2.py3-none-any.whl (26 kB)
Requirement already satisfied: ascii in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from lightnovel-crawler) (3.6)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.8.0 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from lightnovel-crawler) (4.11.1)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from lightnovel-crawler) (2.28.1)
Requirement already satisfied: ebooklib<1.0.0,>=0.17.0 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from lightnovel-crawler) (0.17.1)
Collecting lightnovel-crawler                             Using cached lightnovel_crawler-3.0.0-py3-none-any.whl (499 kB)                                               Requirement already satisfied: pyease-grpc>=1.3.0 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from lightnovel-crawler) (1.3.0)
Requirement already satisfied: lxml<5.0.0,>=4.0.0 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from lightnovel-crawler) (4.9.1)                     Requirement already satisfied: regex in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from lightnovel-crawler) (2022.9.13)
Requirement already satisfied: pyjsparser>=2.5.1 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from js2py==0.71->lightnovel-crawler) (2.7.1)         Requirement already satisfied: tzlocal>=1.2 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from js2py==0.71->lightnovel-crawler) (4.2)
Requirement already satisfied: six>=1.10 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from js2py==0.71->lightnovel-crawler) (1.16.0)                Requirement already satisfied: soupsieve>1.2 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from beautifulsoup4<5.0.0,>=4.8.0->lightnovel-crawler) (2.3.2.post1)                                              Requirement already satisfied: requests-toolbelt>=0.9.1 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from cloudscraper>=1.2.60->lightnovel-crawler) (0.10.0)                                                Requirement already satisfied: pyparsing>=2.4.7 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from cloudscraper>=1.2.60->lightnovel-crawler) (3.0.9)
Requirement already satisfied: webencodings in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from html5lib~=1.1->lightnovel-crawler) (0.5.1)            Requirement already satisfied: wcwidth in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from prompt-toolkit~=3.0->lightnovel-crawler) (0.2.5)
Requirement already satisfied: protobuf>=3.19.0 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from pyease-grpc>=1.3.0->lightnovel-crawler) (4.21.7)  Requirement already satisfied: text-unidecode>=1.3 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from python-slugify<7.0.0,>=4.0.0->lightnovel-crawler) (1.3)                                                Requirement already satisfied: idna<4,>=2.5 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from requests<3.0.0,>=2.20.0->lightnovel-crawler) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from requests<3.0.0,>=2.20.0->lightnovel-crawler) (1.26.12)
Requirement already satisfied: certifi>=2017.4.17 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from requests<3.0.0,>=2.20.0->lightnovel-crawler) (2022.9.24)
Requirement already satisfied: charset-normalizer<3,>=2 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from requests<3.0.0,>=2.20.0->lightnovel-crawler) (2.1.1)
Requirement already satisfied: pytz-deprecation-shim in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from tzlocal>=1.2->js2py==0.71->lightnovel-crawler) (0.1.0.post0)
Requirement already satisfied: tzdata in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from pytz-deprecation-shim->tzlocal>=1.2->js2py==0.71->lightnovel-crawler) (2022.4)
$

========================================================
╭╮╱╱╱╱╱╱╭╮╱╭╮╱╱╱╱╱╱╱╱╱╱╱╱╭╮╱╭━━━╮╱╱╱╱╱╱╱╱╱╭╮            ┃┃╱╱╱╱╱╱┃┃╭╯╰╮╱╱╱╱╱╱╱╱╱╱╱┃┃╱┃╭━╮┃╱╱╱╱╱╱╱╱╱┃┃
┃┃╱╱╭┳━━┫╰┻╮╭╋━╮╭━━┳╮╭┳━━┫┃╱┃┃╱╰╋━┳━━┳╮╭╮╭┫┃╭━━┳━╮
┃┃╱╭╋┫╭╮┃╭╮┃┃┃╭╮┫╭╮┃╰╯┃┃━┫┃╱┃┃╱╭┫╭┫╭╮┃╰╯╰╯┃┃┃┃━┫╭╯
┃╰━╯┃┃╰╯┃┃┃┃╰┫┃┃┃╰╯┣╮╭┫┃━┫╰╮┃╰━╯┃┃┃╭╮┣╮╭╮╭┫╰┫┃━┫┃
╰━━━┻┻━╮┣╯╰┻━┻╯╰┻━━╯╰╯╰━━┻━╯╰━━━┻╯╰╯╰╯╰╯╰╯╰━┻━━┻╯
╱╱╱╱╱╭━╯┃ v2.34.0
╱╱╱╱╱╰━━╯ 🔗 https://github.com/dipu-bd/lightnovel-crawler
--------------------------------------------------------
 📦 VERSION 3.0.1 IS NOW AVAILABLE!
  ➡ Upgrade using pip install -U lightnovel-crawler
--------------------------------------------------------
Failed to load module: /data/data/com.termux/files/home/.lncrawl/sources/en/a/allnovel.py                       Failed to load module: /data/data/com.termux/files/home/.lncrawl/sources/en/n/novelfull.py
Failed to load module: /data/data/com.termux/files/home/.lncrawl/sources/en/n/novelfullplus.py                  Failed to load module: /data/data/com.termux/files/home/.lncrawl/sources/en/n/novelupdatescc.py
Failed to load module: /data/data/com.termux/files/home/.lncrawl/sources/en/r/readlightnovelsnet.py             Failed to load module: /data/data/com.termux/files/home/.lncrawl/sources/en/r/readnovelfull.py                  Failed to load module: /data/data/com.termux/files/home/.lncrawl/sources/en/r/readwn.py
Failed to load module: /data/data/com.termux/files/home/.lncrawl/sources/en/w/webnovel.py
Failed to load module: /data/data/com.termux/files/home/.lncrawl/sources/en/w/wuxiacom.py                       Failed to load module: /data/data/com.termux/files/home/.lncrawl/sources/en/n/novelmt.py                        Failed to load module: /data/data/com.termux/files/home/.lncrawl/sources/en/l/ltnovel.py
Failed to load module: /data/data/com.termux/files/home/.lncrawl/sources/en/m/myboxnovel.py                     Failed to load module: /data/data/com.termux/files/home/.lncrawl/sources/en/a/allnovelfull.py                   Failed to load module: /data/data/com.termux/files/home/.lncrawl/sources/en/m/mangarockteam.py
Failed to load module: /data/data/com.termux/files/home/.lncrawl/sources/en/h/hotnovelfull.py
Failed to load module: /data/data/com.termux/files/home/.lncrawl/sources/en/f/freewebnovel.py                   Failed to load module: /data/data/com.termux/files/home/.lncrawl/sources/en/h/hs2ppe.py                         Failed to load module: /data/data/com.termux/files/home/.lncrawl/sources/en/i/inkitt.py
Failed to load module: /data/data/com.termux/files/home/.lncrawl/sources/en/i/snowycodex.py                     Failed to load module: /data/data/com.termux/files/home/.lncrawl/sources/en/l/lightnovelmeta.py                 Failed to load module: /data/data/com.termux/files/home/.lncrawl/sources/en/n/novel35.py
Failed to load module: /data/data/com.termux/files/home/.lncrawl/sources/en/n/novelbin.py                       Failed to load module: /data/data/com.termux/files/home/.lncrawl/sources/en/n/novelfullme.py                    Failed to load module: /data/data/com.termux/files/home/.lncrawl/sources/en/n/novelhulk.py
Failed to load module: /data/data/com.termux/files/home/.lncrawl/sources/en/n/novelmtl.py                       Failed to load module: /data/data/com.termux/files/home/.lncrawl/sources/en/n/novelnext.py                      Failed to load module: /data/data/com.termux/files/home/.lncrawl/sources/en/w/wuxiamtl.py
Failed to load module: /data/data/com.termux/files/home/.lncrawl/sources/en/w/wuxiahub.py                       Failed to load module: /data/data/com.termux/files/home/.lncrawl/sources/en/w/wuxianovelhub.py                  Failed to load module: /data/data/com.termux/files/home/.lncrawl/sources/en/w/wuxiapub.py
Failed to load module: /data/data/com.termux/files/home/.lncrawl/sources/en/w/wuxiav.py                         Failed to load module: /data/data/com.termux/files/home/.lncrawl/sources/en/w/wuxiar.py                         Failed to load module: /data/data/com.termux/files/home/.lncrawl/sources/en/w/wuxiau.py
Failed to load module: /data/data/com.termux/files/home/.lncrawl/sources/en/w/wuxiax.py                         Failed to load module: /data/data/com.termux/files/home/.lncrawl/sources/en/w/wuxiaz.py                         Failed to load module: /data/data/com.termux/files/home/.lncrawl/sources/ru/bestmanga.py
                                                        ➡ Press  Ctrl + C  to exit                              
? Enter novel page url or query novel:

**Comment by dipu-bd** [comment] 2022-10-12 14:06
Duplicate of #1713

**Closed by dipu-bd** 2022-10-12 14:06 UTC
