### ISSUE TITLE
Incorrect loading of chapters from mtlnation.com

### ISSUE THREAD

**Issue by LisArits** [dipu-bd/lightnovel-crawler#1562] opened 2022-09-09 02:22 UTC
When loading chapters, all the text in the chapters is mixed up

original
![1](https://user-images.githubusercontent.com/113008317/189258688-95e4bd52-f11a-4704-a909-ee9c5be9bade.png)

loaded
![2](https://user-images.githubusercontent.com/113008317/189258751-8394138b-bf0a-4419-9b1e-00d18d3cd5b4.png)

**Comment by budikesuma** [comment] 2022-09-09 11:10
> When loading chapters, all the text in the chapters is mixed up
> 

@LisArits 

Why didn't I experience it?
What is your novel link?

No problems here:
   Test link: https://mtlnation.com/novel/xuanhuan-me-begin-to-cultivate-a-great-emperor
.
.
![Screenshot_20220909-180324_Browser](https://user-images.githubusercontent.com/50254552/189336869-4af7c654-940b-422b-993c-9f91c9e89ec5.jpg)
.
![Screenshot_20220909-180345_MiXplorer](https://user-images.githubusercontent.com/50254552/189336883-f3275d2e-7b72-4d76-ab01-52c20680f83e.jpg)
.
![Screenshot_20220909-180235_Browser](https://user-images.githubusercontent.com/50254552/189336890-b3a39904-0be1-4dfa-9958-160dbaad8682.jpg)
.
![Screenshot_20220909-180254_MiXplorer](https://user-images.githubusercontent.com/50254552/189336896-1b7ffd13-9d11-453a-91d4-26e492ac7746.jpg)
.

**Comment by dipu-bd** [comment] 2022-09-09 11:38
It should be a source issue

**Comment by idMysteries** [comment] 2022-09-09 12:11
@dipu-bd This is not a source error. I checked the source and everything is fine there.

**Comment by idMysteries** [comment] 2022-09-09 12:11
https://mtlnation.com/novel/universes-ultimate-boss/chapter-590/

**Comment by idMysteries** [comment] 2022-09-09 12:13
![изображение](https://user-images.githubusercontent.com/11484976/189347466-facbda42-6a20-4e0b-adc2-efc7c4a2d9dc.png)
data['content'] is correct.

**Comment by LisArits** [comment] 2022-09-10 07:04
@budikesuma 

I usually have 1-100, sometimes 1-200 chapters download normally, but then confusion begins, or the first downloaded chapter, for example 601, downloads normally, and then 602, etc. confusion begins. I recorded a short video of the whole process, maybe I'm doing something wrong. You can scroll through the moments of loading and waiting for the beginning of the comparison of chapters after 3 minutes

https://youtu.be/zmW-K1KTEhs

**Comment by idMysteries** [comment] 2022-09-10 08:01
@dipu-bd The mtlnation API returns different results in the browser and in the crawler. Why? Cookies?

**Comment by idMysteries** [comment] 2022-09-10 08:40
The problem is clearly on the site side. Sometimes the api gives the right result, sometimes the wrong one.

**Comment by idMysteries** [comment] 2022-09-10 08:43
@dipu-bd you can close the issue.
![изображение](https://user-images.githubusercontent.com/11484976/189475902-06b64a1a-adb0-4f07-9ea2-3b670f58df6a.png)

**Comment by budikesuma** [comment] 2022-09-11 02:34
> 
> I usually have 1-100, sometimes 1-200 chapters download normally, but then confusion begins, or the first downloaded chapter, for example 601, downloads normally, and then 602, etc. confusion begins. I recorded a short video of the whole process, maybe I'm doing something wrong. You can scroll through the moments of loading and waiting for the beginning of the comparison of chapters after 3 minutes
> 
@LisArits 

Could there be a problem with your platform?
I tried downloading the same novel and checking the same chapter range but no problem.
Oh yeah, I'm using the Google Colab platform with my own login script, does that make a difference?

You can check, I will upload the epub here: 
.
`NOTE: ` please remove the `.png` suffix (since github only accepted image/video extensions).
.
![UniverseS Ultimate Boss c601-700 epub](https://user-images.githubusercontent.com/50254552/189509223-4c2749a4-1ea9-474d-87b8-a8b7164ff8d8.png)
.
.
![Screenshot_20220911-091136_Browser](https://user-images.githubusercontent.com/50254552/189509335-a4fe906b-ed72-48fd-b856-76ad3db6f640.jpg)

![Screenshot_20220911-085458_Browser](https://user-images.githubusercontent.com/50254552/189509337-b9c7868c-a91a-45e1-92a9-92844fd4a113.jpg)

![Screenshot_20220911-091245_MiXplorer](https://user-images.githubusercontent.com/50254552/189509339-2034379e-0b59-4fc2-b660-1ee4577f05c7.jpg)

![Screenshot_20220911-085633_Browser](https://user-images.githubusercontent.com/50254552/189509340-c5e9fec2-3f69-4a44-a999-a24ab8ab89e2.jpg)

![Screenshot_20220911-085655_MiXplorer](https://user-images.githubusercontent.com/50254552/189509342-937febb3-53e0-460f-af2b-add1bb06c618.jpg)
.

**Comment by dipu-bd** [comment] 2022-09-11 10:04
I guess that they are trying to prevent crawlers at all cost.

**Comment by dipu-bd** [comment] 2022-10-09 15:08
I figured out the issue. The site itself is unstable. I got different text from it for the same chapter.

**Closed by dipu-bd** 2022-10-09 15:08 UTC
Labels: source-issue

**Comment by idMysteries** [comment] 2022-10-09 17:59
@dipu-bd https://github.com/dipu-bd/lightnovel-crawler/issues/1562?notification_referrer_id=NT_kwDOAK8_MLM0MzY0Mzg0MTIzOjExNDg0OTc2#issuecomment-1242670671
..... 29 days ago...

**Comment by dipu-bd** [comment] 2022-10-09 18:44
> @dipu-bd [#1562 (comment)](https://github.com/dipu-bd/lightnovel-crawler/issues/1562#issuecomment-1242670671) ..... 29 days ago...

Yeah, I did not have time to verify it until today
